### ISSUE TITLE
Incorrect implementation of Zce PUSH instruction 

### ISSUE THREAD

**Issue by Lukacma** [plctlab/llvm-project#22]
The latest version of ZCE specs, mentions that inclusion of _areg_list_ is optional as can be seen in this snippet :

![image](https://user-images.githubusercontent.com/46606997/129385103-36cc1e98-00ec-4c80-ac02-f932893c6ca5.png)

However current definition of the instruction doesn't allow for this selection and presumes that _areg_list_ is always included.

**Comment by Xinlong-WU** [comment]
ok, we will fix it

**Comment by Marcythm** [comment]
Fixed.
