### ISSUE TITLE
Auto compressing Zce instructions

### ISSUE THREAD

**Issue by abukharmeh** [plctlab/llvm-project#30]
Hi, 

I am testing Zce assembler, and it feels like the assembler does not check if it can use compressed Zce instructions.

For instance, trying the following assembly code:

```
not x15,x15
add x15,x0,x15
```

I would expect the assembler to generate two compressed instruction (c.not and c.mv), however, it generate a compressed instruction for the add and 32 bit instruction (xori -1) for c.not

![image](https://user-images.githubusercontent.com/24764074/142021372-479a9078-8936-4217-b849-11b8a459bb0b.png)

Using Zce compressed instructions explicitly work, but auto compression should also work. 

Kind regards,
Ibrahim.

**Comment by Xinlong-WU** [comment]
Hi, Ibrahim

Yes, in fact, we are not optimising/compressing instructions at the assembly level. 
We are generating Zce assembly instructions by changing the **llvm IR** instructions. 
that's why the `llvm-mc` will not compress the code. it's only work is to generate the **obj file**.
You can try writing c source programs or LLVM IR programs to check the compression efficiency.
this link may helps you. https://www.wulongxin.com/index.php/archives/950/

Yours sincerely ,
Wu Xinlong

**Comment by ScottEgerton** [comment]
Hi,

Please correct me if I’m wrong but I believe that support for this kind of optimisation could be added in a similar fashion to what has been done here https://github.com/plctlab/llvm-project/blob/647625214a658572ac0beea6800b4abb07d46530/llvm/lib/Target/RISCV/RISCVInstrInfoZce.td#L710.

Kind regards,
Scott

**Comment by Xinlong-WU** [comment]
ok, we will take a try

**Comment by luke957** [comment]
> Hi,
> 
> Please correct me if I’m wrong but I believe that support for this kind of optimisation could be added in a similar fashion to what has been done here
> 
> https://github.com/plctlab/llvm-project/blob/647625214a658572ac0beea6800b4abb07d46530/llvm/lib/Target/RISCV/RISCVInstrInfoZce.td#L710
> 
> Kind regards, Scott

Thanks for the infomation.

**Comment by luke957** [comment]
> Hi,
> 
> I am testing Zce assembler, and it feels like the assembler does not check if it can use compressed Zce instructions.
> 
> For instance, trying the following assembly code:
> 
> ```
> not x15,x15
> add x15,x0,x15
> ```
> 
> I would expect the assembler to generate two compressed instruction (c.not and c.mv), however, it generate a compressed instruction for the add and 32 bit instruction (xori -1) for c.not
> 
> ![image](https://user-images.githubusercontent.com/24764074/142021372-479a9078-8936-4217-b849-11b8a459bb0b.png)
> 
> Using Zce compressed instructions explicitly work, but auto compression should also work.
> 
> Kind regards, Ibrahim.

For now we have implemented auto compression for zcee and NOT NEG, so you can try your assembly code again. We will try to fix other instructions during the following days. Thanks.

**Comment by abukharmeh** [comment]
Excellent, thank you for that.

**Comment by abukharmeh** [comment]
We appear to have a regression where we dont auto compress lb to cm.lb etc while I expect them to be auto compressed ?
