### ISSUE TITLE
PUSHPOP specific flags appear not to work with code gen

### ISSUE THREAD

**Issue by abukharmeh** [plctlab/llvm-project#31]
Hi, 

I am trying pushpop code gen implementation, It appears that code gen does indeed infer pushpop when I use march  rv32imaczcea0p50, but it appears that if I have march rv32imac and the flags for zce, namely mzce-cpush-cpop and mzce-push-pop, it does not infer them

I think the assembler work in both cases, could you please confirm and fix this issue. 

Kind regards, 
Ibrahim.

**Comment by SForeKeeper** [comment]
Hi, 

I need to make sure a few things. In previous versions (switches are not implemented, all switches are enabled), would it work? And it's only these two flags are not working while other flags are functioning properly, is that correct?

Regards,
Liam.

**Comment by abukharmeh** [comment]
Yes, I am running latest version from github.  All other switches including these ones work for assembler. 

I am just starting to test code gen, I only tested  `mzce-cpush-cpop and mzce-push-pop` and they did not work, the compiler uses push and pop instructions when you specify `march=rv32imaczcea0p50` without any additional switches but it does not when you specify  `march=rv32imac` and push pop switches.

**Comment by SForeKeeper** [comment]
Hi,

There are two commits merged into riscv-zce-extension branch. It should fix your problem. Please test it out and give feedbacks. 

Thank you.

**Comment by abukharmeh** [comment]
Hi @SForeKeeper 

Yes, that sorted it out.

Thank you.
