### ISSUE TITLE
Zce Branch: BEQI and BNEI wrong encoding

### ISSUE THREAD

**Issue by abukharmeh** [plctlab/llvm-project#34]
Hi

It appears that BEQI and BNEI are encoded as they were in 0.40.1. In release 0.50.1, we compare against rs2 instead of rs1, and the immediate location was swapped around

This was changed in this commit, https://github.com/riscv/riscv-code-size-reduction/commit/4838a095c90440c6bf73117aaf773217725bf033

Could you please update this to match 0.50.1

Thank you, 
Ibrahim

**Comment by ChunyuLiao** [comment]
ok, ，thanks , we will fix it

**Comment by luke957** [comment]
Hi, we have updated the repo to fix the encoding for beqi and bnei. Also we have added a mi pass to improve instruction compressing. Changes on branch riscv-zce-extension have also been cherry-picked to riscv-zce-llvm14. So it is suggested to try the branch riscv-zce-llvm14.

**Comment by abukharmeh** [comment]
Sorry for late reply, I confirm that both issues appear to be fixed now, thank you.
