### ISSUE TITLE
请问现在的版本支持vector extension的OpenMP和pthreads程序吗？

### ISSUE THREAD

**Issue by zhewenhu** [plctlab/llvm-project#35]
我可以编译普通版本的OpenMP和pthreads程序，但是加入--target=riscv64-unknown-elf -march=rv64gcv1p0 -menable-experimental-extensions -DENABLE_OPENMP -fopenmp后则会报错，请问是现在版本不支持还是配置有误？

**Comment by ChunyuLiao** [comment]
rvv-iscas分支已经暂停开发很久了。建议试试upstream llvm的支持情况，且rvv的版本是0.10

**Comment by zhewenhu** [comment]
你好，我想要编译一个benchmark (https://github.com/RALC88/riscv-vectorized-benchmark-suite/tree/rvv-1.0)，里面用的应该是 rvv 1.0，upstream是否就不支持了？

**Comment by XDUFanYang** [comment]
> 你好，我想要编译一个benchmark ([https://github.com/RALC88/riscv-vectorized-benchmark-suite/tree/rvv-1.0)，里面用的应该是](https://github.com/RALC88/riscv-vectorized-benchmark-suite/tree/rvv-1.0)%EF%BC%8C%E9%87%8C%E9%9D%A2%E7%94%A8%E7%9A%84%E5%BA%94%E8%AF%A5%E6%98%AF) rvv 1.0，upstream是否就不支持了？

您好，这个仓库已经很久没有维护过了，您可以用这个[仓库](https://github.com/plctlab/riscv-vectorized-benchmark-suite/tree)编译benchmark，这里支持vector extension的OpenMP和pthreads程序。
