### ISSUE TITLE
make check-llvm-mc-riscv-rvZce... 

### ISSUE THREAD

**Issue by kczmudzi** [plctlab/llvm-project#45]
...should be make check-llvm-mc-riscv-rvzce

Also, how do I use test these extensions?  What relations do they have to the Zca Zcf Zcb Zcmb Zcmp Zcmpe Zcmt extensions?

**Comment by Xinlong-Wu** [comment]
the command `check-llvm-mc-riscv-rvzce` will run & test all files which is stored in the path `llvm/test/MC/RISCV/rvZce`

> Also, how do I use test these extensions? What relations do they have to the Zca Zcf Zcb Zcmb Zcmp Zcmpe Zcmt extensions?

I have written an article before, [Compile a C file with Zce ext in LLVM](https://www.wulongxin.com/index.php/archives/950/), it may be a bit outdated. you need to replace `zce0p50` with what you want to test. eg. `-march=rv32imac_zcmt0p70`
