### ISSUE TITLE
[simd][OSPP] simd test flamework issues

### ISSUE THREAD

**Issue by joy2myself** [plctlab/llvm-project#54]
simd test flamework directory structure：

```
- simd/
	- simd.traits/
		- is_abi_tag.pass.cpp
		- is_simd.pass.cpp
		- is_simd_mask.pass.cpp
		- is_simd_flag_type.pass.cpp
		- simd_size.pass.cpp
		- memory_alignment.pass.cpp
		- rebind_simd.pass.cpp
		- resize_simd.pass.cpp
	- simd.casts/
		- static_simd_cast.pass.cpp
		- simd_cast.pass.cpp
		- to_fixed_size.pass.cpp
		- to_native.pass.cpp
		- to_compatible.pass.cpp
		- split.pass.cpp
		- split_by.pass.cpp
		- concat.pass.cpp
	- simd.whereexpr/
		- const_where_expression.pass.cpp
		- where_expression.pass.cpp
	- simd.reference/
		- reference_value_type.pass.cpp
		- reference_operators.pass.cpp
		- reference_swap.pass.cpp
	- simd.class/
		- simd_width.pass.cpp
		- simd_ctor.pass.cpp
		- simd_copy.pass.cpp
		- simd_subscr.pass.cpp
		- simd_unary.pass.cpp
	- simd.nonmembers/
		- simd_binary.pass.cpp
		- simd_cassign.pass.cpp
		- simd_comparison.pass.cpp
		- simd_reductions.pass.cpp
		- simd_alg.pass.cpp
		- simd.math/
			- ......
	- simd.mask.class/
		- simd_mask_width.pass.cpp
		- simd_mask_ctor.pass.cpp
		- simd_mask_copy.pass.cpp
		- simd_mask_subscr.pass.cpp
		- simd_mask_unary.pass.cpp
	- simd.mask.nonmembers/
		- simd_mask_binary.pass.cpp
		- simd_mask_cassign.pass.cpp
		- simd_mask_comparison.pass.cpp
		- simd_mask_reductions.pass.cpp
		- simd_mask_where.pass.cpp
	- test_utils.h
```

- [x] is_abi_tag.pass.cpp
- [x] is_simd.pass.cpp
- [x] is_simd_mask.pass.cpp
- [x] is_simd_flag_type.pass.cpp
- [x] simd_size.pass.cpp (Missing false SFINAE test cases)
- [x] memory_alignment.pass.cpp (Missing false SFINAE test cases)
- [x] rebind_simd.pass.cpp (Missing false SFINAE test cases)
- [x] resize_simd.pass.cpp (Missing false SFINAE test cases)
- [x] static_simd_cast.pass.cpp (Missing false SFINAE test cases)
- [x] simd_cast.pass.cpp (Missing false SFINAE test cases)
- [x] to_fixed_size.pass.cpp
- [x] to_native.pass.cpp (Missing false SFINAE test cases)
- [x] to_compatible.pass.cpp (Missing false SFINAE test cases)
- [x] split.pass.cpp
- [x] split_by.pass.cpp
- [x] concat.pass.cpp
- [x] const_where_expression.pass.cpp
- [x] where_expression.pass.cpp
- [x] reference_value_type.pass.cpp
- [x] reference_operators.pass.cpp
- [x] reference_swap.pass.cpp
- [x] simd_width.pass.cpp
- [x] simd_ctor.pass.cpp
- [x] simd_copy.pass.cpp
- [x] simd_subscr.pass.cpp
- [x] simd_unary.pass.cpp
- [x] simd_binary.pass.cpp
- [x] simd_cassign.pass.cpp
- [x] simd_comparison.pass.cpp
- [x] simd_reductions.pass.cpp
- [x] simd_alg.pass.cpp
- [x] simd.math/ (Math library related tests do not need to be added temporarily)
- [x] simd_mask_width.pass.cpp
- [x] simd_mask_ctor.pass.cpp
- [x] simd_mask_copy.pass.cpp
- [x] simd_mask_subscr.pass.cpp
- [x] simd_mask_unary.pass.cpp
- [x] simd_mask_binary.pass.cpp
- [x] simd_mask_cassign.pass.cpp
- [x] simd_mask_comparison.pass.cpp
- [x] simd_mask_reductions.pass.cpp
- [x] simd_mask_where.pass.cpp

**Comment by fepicture** [comment]
still lack of some issue about `operator` :
simd.reference:
reference_value_type.pass (I cannot change the directly call way)

simd.class
simd.unary.pass (what is operator ++(int val) ??, I did not find any clue)

simd.where
where_expression.pass (what is operator ++(int val) , I did not find any clue)
const_where_expression.pass ( operator~ return simd_mask)
