### ISSUE TITLE
RISC-V-P扩展中的UKSTSA32指令存在编码错误

### ISSUE THREAD

**Issue by ByeBeihai** [plctlab/llvm-project#56]
尊敬的开发者您好，我正在使用贵实验室的llvm编译risc-v-p指令来测试我的处理器。
我使用的是**p-extension-andes-v1**分支的最新commit版本。
在测试中我注意到，如果使用内联汇编写一条UKSTSA32指令（如下）

**asm volatile("ukstsa32 t5,t3,t4");**

那么我会得到这样的编译结果（使用objdump进行反汇编）

**80000028:	e3de3f77          	0xe3de3f77**

即该指令的结果被翻译成了如下的二进制码：
**1110001 11101 11100 011 11110 1110111**

注意这条指令的**14-12**位为：**011**

但是在目前的RISC-V-P扩展规范中，UKSTSA32的格式应该如下：
![image](https://user-images.githubusercontent.com/71160978/197506732-ec22b34e-f97b-41a9-ab33-1dd58521e516.png)
UKSTSA32指令的**14-12**位应该为：**010**

请问这是否是一个编译器的bug？还是我选择了错误的分支进行部署？

**Comment by sunshaoce** [comment]
您好！这个问题已经被修复了。
p-extension-andes-v1分支已经是最新的P-ext代码了，但可能和变化中的P-ext Spec有出入。
感谢您的反馈！
