### ISSUE TITLE
ninja编译失败了

### ISSUE THREAD

**Issue by DYY-Drummer** [plctlab/llvm-project#63]
ubuntu 20.04，使用编译命令`cmake -G "Ninja" -DLLVM_ENABLE_PROJECTS="clang" -DLLVM_TARGETS_TO_BUILD="RISCV" -DCMAKE_BUILD_TYPE="Release"  ../llvm` 编译失败。报错如下：
[1893/2968] Building CXX object tools/...Files/obj.clangSema.dir/SemaExpr.cpp.o
FAILED: tools/clang/lib/Sema/CMakeFiles/obj.clangSema.dir/SemaExpr.cpp.o 
/usr/bin/c++  -DGTEST_HAS_RTTI=0 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Itools/clang/lib/Sema -I/home/dyy/llvm-project/clang/lib/Sema -I/home/dyy/llvm-project/clang/include -Itools/clang/include -Iinclude -I/home/dyy/llvm-project/llvm/include -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-redundant-move -Wno-pessimizing-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wmisleading-indentation -fdiagnostics-color -ffunction-sections -fdata-sections -fno-common -Woverloaded-virtual -fno-strict-aliasing -O3 -DNDEBUG    -fno-exceptions -fno-rtti -std=c++14 -MD -MT tools/clang/lib/Sema/CMakeFiles/obj.clangSema.dir/SemaExpr.cpp.o -MF tools/clang/lib/Sema/CMakeFiles/obj.clangSema.dir/SemaExpr.cpp.o.d -o tools/clang/lib/Sema/CMakeFiles/obj.clangSema.dir/SemaExpr.cpp.o -c /home/dyy/llvm-project/clang/lib/Sema/SemaExpr.cpp
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
[1895/2968] Building CXX object tools/...es/obj.clangSema.dir/SemaExprCXX.cpp.o
ninja: build stopped: subcommand failed.

**Comment by Xinlong-Wu** [comment]
请详细说明一下是哪一个分支

**Comment by DYY-Drummer** [comment]
llvmorg-15.0.0

**Comment by DYY-Drummer** [comment]
> 请详细说明一下是哪一个分支

llvmorg-15.0.0

**Comment by Xinlong-Wu** [comment]
`llvmorg-15.0.0`的话应该是上游的分支吧。那不是我们维护的，所以我们只能尽量给出我们的建议。
请问您使用的机器的核数和内存大小分别是多少。
通过`Killed signal terminated program cc1plus`猜测有可能是因为内存不够导致进程被杀掉了。
我们的经验大概是每一个核/线程需要16G左右的内存，可以尝试使用`-j`命令限制同时执行编译的线程数试试

**Comment by DYY-Drummer** [comment]
> `llvmorg-15.0.0`的话应该是上游的分支吧。那不是我们维护的，所以我们只能尽量给出我们的建议。 请问您使用的机器的核数和内存大小分别是多少。 通过`Killed signal terminated program cc1plus`猜测有可能是因为内存不够导致进程被杀掉了。 我们的经验大概是每一个核/线程需要16G左右的内存，可以尝试使用`-j`命令限制同时执行编译的线程数试试

明白了，谢谢您，我的运行内存确实只有4G

**Comment by Xinlong-Wu** [comment]
只有4g的话，可以通过软件包的方式安装llvm，或者使用`-DLLVM_ENABLE_PROJECTS`参数仅编译必要的项目，如`-DLLVM_ENABLE_PROJECTS="clang"`

我就先把这个issue关掉了，如果还有问题您再打开
